# Permalinks
permalink:           pretty

# Setup
title:               Arne Groskurth
tagline:             Climbing & Computer Science
url:                 http://arne-groskurth.de
paginate:            3
paginate_path:       "/blog/page-:num/"
baseurl:             ""
excerpt_separator:   "<!--more-->"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Arne Groskurth
  url:               http://arne-groskurth.de
  email:             kontakt@arne-groskurth.de

# Custom vars
github:
  repo:              https://github.com/arnegroskurth/arnegroskurth.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
